version: 2.1

jobs:
  arm-build:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - checkout
      - run: uname -a
      - run:
          name: "Build"
          command: make
      - run:
          name: "Run"
          command: ./main

  x86_64-build:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: medium
    steps:
      - checkout
      - run: uname -a
      - run:
          name: "Build"
          command: make
      - run:
          name: "Run"
          command: ./main

workflows:
  main-workflow:
    jobs:
      - arm-build
      - x86_64-build